// src/db/type/winelist.ts
import type { Wine } from './wine';

export const winelist: Wine[] = [
  {
    id: 'w1',
    image: '/winelist/w1_white54_1.png',

    // 퀴즈 매칭용
    type: 'white',
    region: 'oceania',
    body: 'medium',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    // 전시용
    nameKo: '루이라뚜르 그랑 아데슈 샤르도네',
    nameEn: "Louis Latour, Grand Ardeche Chardonnay",
    originalPrice: 60000,
    salePrice: 53000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.5,
    reviewCount: 12,
  },
  // 나머지 와인도 같은 패턴으로 추가
  {
    id: 'w2',
    image: '/winelist/w2_white54_2.png',

    type: 'white',
    region: 'southamerica',
    body: 'medium',
    tannin: 'low',
    acidity: 'low',
    sweetness: 'medium',

    nameKo: '알파카 모스카토',
    nameEn: "Alpaca Moscato",
    originalPrice: 15000,
    salePrice: 12000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.2,
    reviewCount: 24,
  },
  {
    id: 'w3',
    image: '/winelist/w3_white54_3.png',

    type: 'white',
    region: 'oceania',
    body: 'medium',
    tannin: 'medium',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '피에르 샤니에 상세르 블랑',
    nameEn: "Pierre Chainier Sancerre Blanc",
    originalPrice: 55000,
    salePrice: 55000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.0,
    reviewCount: 16,
  },
  {
    id: 'w4',
    image: '/winelist/w4_white54_4.png',

    type: 'white',
    region: 'northamerica',
    body: 'light',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '데블스 카니발 페노메날 소비뇽',
    nameEn: "Devil's Carnaval Phenomenal Sauvignon",
    originalPrice: 37000,
    salePrice: 35000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.9,
    reviewCount: 17,
  },
  {
    id: 'w5',
    image: '/winelist/w5_white54_5.png',

    type: 'white',
    region: 'southamerica',
    body: 'light',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '물리노 페르 에 필스 샤블리',
    nameEn: "Mouloneau Pere Et Fils Chablis",
    originalPrice: 71000,
    salePrice: 71000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.5,
    reviewCount: 8,
  },
  {
    id: 'r1',
    image: '/winelist/r1_red53_1.png',

    type: 'red',
    region: 'southamerica',
    body: 'full',
    tannin: 'high',
    acidity: 'low',
    sweetness: 'low',

    nameKo: '하모늄 네로 다볼라 시칠리아',
    nameEn: "Harmonium Nero d Avola Sicilia",
    originalPrice: 36000,
    salePrice: 36000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.8,
    reviewCount: 28,
  },  
  {
    id: 'r2',
    image: '/winelist/r2_red53_2.png',

    type: 'red',
    region: 'europe',
    body: 'full',
    tannin: 'low',
    acidity: 'medium',
    sweetness: 'low',

    nameKo: '레드 엔젤 온 더 문라이트 피노 네로',
    nameEn: "Red Angel On The Moonlight Pinot Nero",
    originalPrice: 55000,
    salePrice: 55000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.9,
    reviewCount: 34,
  },
  {
    id: 'r3',
    image: '/winelist/r3_red53_3.png',

    type: 'red',
    region: 'europe',
    body: 'full',
    tannin: 'high',
    acidity: 'low',
    sweetness: 'low',

    nameKo: '샤또 라 프랑스 델옴므 메독',
    nameEn: "Château La France Delhomme Médoc",
    originalPrice: 63000,
    salePrice: 59000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.1,
    reviewCount: 8,
  },
  {
    id: 'r4',
    image: '/winelist/r4_red53_4.png',

    type: 'red',
    region: 'northamerica',
    body: 'full',
    tannin: 'medium',
    acidity: 'low',
    sweetness: 'low',

    nameKo: '테누타 디 비세르노',
    nameEn: "Tenuta di Biserno",
    originalPrice: 125000,
    salePrice: 125000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.5,
    reviewCount: 8,
  },
  {
    id: 'r5',
    image: '/winelist/r5_red53_5.png',

    type: 'red',
    region: 'europe',
    body: 'medium',
    tannin: 'medium',
    acidity: 'medium',
    sweetness: 'low',

    nameKo: '브라우네베르거 만델그라벤 피노누아',
    nameEn: "Brauneberger Mandelgraben Pinot Noir",
    originalPrice: 25000,
    salePrice: 25000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.0,
    reviewCount: 24,
  },
  {
    id: 'o1',
    image: '/winelist/o1_rose55_1.png',

    type: 'rose',
    region: 'europe',
    body: 'light',
    tannin: 'low',
    acidity: 'medium',
    sweetness: 'high',

    nameKo: '유니콘 로제 버블스',
    nameEn: "Unicorn Rose Bubbles",
    originalPrice: 27000,
    salePrice: 27000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.1,
    reviewCount: 21,
  },
  {
    id: 'o2',
    image: '/winelist/o2_rose55_2.png',

    type: 'rose',
    region: 'europe',
    body: 'medium',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '폴 당장 뀌베 로제',
    nameEn: "PAUL DANGIN CUVEE ROSE BRUT",
    originalPrice: 21000,
    salePrice: 21000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.9,
    reviewCount: 32,
  },
  {
    id: 'o3',
    image: '/winelist/o3_rose55_3.png',

    type: 'rose',
    region: 'oceania',
    body: 'light',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'high',

    nameKo: '루크 벨레어 레어 로즈',
    nameEn: "Luc Belaire Rare Rose",
    originalPrice: 37000,
    salePrice: 37000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.0,
    reviewCount: 11,
  },
  {
    id: 'o4',
    image: '/winelist/o4_rose55_4.png',

    type: 'rose',
    region: 'northamerica',
    body: 'light',
    tannin: 'low',
    acidity: 'medium',
    sweetness: 'high',

    nameKo: '에이 투 지 오레곤 버블스 로제',
    nameEn: "A to Z Wineworks Bubbles Rosé",
    originalPrice: 27000,
    salePrice: 27000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.8,
    reviewCount: 29,
  },
  {
    id: 'o5',
    image: '/winelist/o5_rose55_5.png',

    type: 'rose',
    region: 'europe',
    body: 'medium',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'high',

    nameKo: '루이 부요 크레망 드 부르고뉴 로제',
    nameEn: "Louis Bouillot Cremant De Bourgogne Rose",
    originalPrice: 35000,
    salePrice: 35000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.5,
    reviewCount: 22,
  },
  {
    id: 'c1',
    image: '/winelist/c1_cham56_1.png',

    type: 'champagne',
    region: 'europe',
    body: 'medium',
    tannin: 'low',
    acidity: 'medium',
    sweetness: 'low',

    nameKo: '아구스티 토렐로 마타 그란 리세르바 바리카 카바',
    nameEn: "Agusti Torello Mata Gran Reserva Barrica Cava",
    originalPrice: 58000,
    salePrice: 58000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.5,
    reviewCount: 17,
  },
  {
    id: 'c2',
    image: '/winelist/c2_cham56_2.png',

    type: 'champagne',
    region: 'southamerica',
    body: 'medium',
    tannin: 'low',
    acidity: 'medium',
    sweetness: 'low',

    nameKo: '까시예로 델 디아블로 데블스 브뤼',
    nameEn: "Casillero del Diablo Devil's Brut",
    originalPrice: 44000,
    salePrice: 44000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.5,
    reviewCount: 17,
  },
  {
    id: 'c3',
    image: '/winelist/c3_cham56_3.png',

    type: 'champagne',
    region: 'europe',
    body: 'medium',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '크레망 드 부르고뉴',
    nameEn: "Cremant de Bourgogne",
    originalPrice: 60000,
    salePrice: 60000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.7,
    reviewCount: 16,
  },
  {
    id: 'c4',
    image: '/winelist/c4_cham56_4.png',

    type: 'champagne',
    region: 'europe',
    body: 'light',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '루이 부요 크레망 드 부르고뉴 블랑 드 누아',
    nameEn: "Louis Bouillot Crémant de Bourgogne Blanc de Noirs",
    originalPrice: 75000,
    salePrice: 71000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 3.5,
    reviewCount: 17,
  },
  {
    id: 'c5',
    image: '/winelist/c5_cham56_5.png',

    type: 'champagne',
    region: 'europe',
    body: 'full',
    tannin: 'low',
    acidity: 'high',
    sweetness: 'low',

    nameKo: '어니스트 레미 브뤼 그랑크뤼',
    nameEn: "Ernest Remy Brut Grand Cru",
    originalPrice: 120000,
    salePrice: 120000,
    labels: ['NEW', 'EVENT', 'BEST'],
    rating: 4.0,
    reviewCount: 11,
  }
];
